"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = config("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = config("DEBUG", cast=bool)

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = config("ALLOWED_HOSTS").split(",")


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "apps.account",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "src.utils.middleware.NinjaResponseMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# 语言与时间
LANGUAGE_CODE = "zh-hans"
TIME_ZONE = "Asia/Shanghai"

USE_I18N = True

USE_TZ = True

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


############ 自定义配置 ############
if config("CAPTCHA", cast=bool):
    INSTALLED_APPS.append("captcha")

if config("SIMPLE_UI", cast=bool):
    INSTALLED_APPS.insert(0, "simpleui")

if DEBUG:
    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # 前端本地开发地址
    ]
else:
    CORS_ALLOWED_ORIGINS = config("CORS_ALLOWED_ORIGINS").split(",")

STATIC_URL = "/static/"
STATIC_ROOT = f"/var/www/html/{BASE_DIR.parent.name}/staticfiles/"
STATICFILES_DIRS = [BASE_DIR / "src/static"]
MEDIA_URL = "/media/"  # 访问媒体文件的URL
MEDIA_ROOT = f"/var/www/html/{BASE_DIR.parent.name}/media/"  # 存储上传文件的位置

AUTH_USER_MODEL = "account.CustomUser"  # 自定义用户
# 添加自己的app
INSTALLED_APPS += []


# Celery 配置
CELERY_TIMEZONE = TIME_ZONE  # 与 Django 时区保持一致
CELERY_TASK_TRACK_STARTED = True  # 追踪任务开始状态
if DEBUG:
    CELERY_BROKER_URL = "redis://127.0.0.1:6379/0"  # Redis 消息队列地址
    CELERY_RESULT_BACKEND = "redis://127.0.0.1:6379/1"  # 存储任务结果的数据库地址
else:
    CELERY_BROKER_URL = "redis://redis:6379/0"
    CELERY_RESULT_BACKEND = "redis://redis:6379/1"


# 数据库备份
if config("DB_BACKUP", cast=bool):
    INSTALLED_APPS.append("dbbackup")
    STORAGES = {
        # 1. 默认文件存储（媒体文件）
        "default": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
        },
        # 2. 静态文件存储（避免 staticfiles.E005 报错）
        "staticfiles": {
            "BACKEND": "django.contrib.staticfiles.storage.StaticFilesStorage",
        },
        # 3. dbbackup 专属存储桶 (最新版 django-dbbackup 要求的格式)
        "dbbackup": {
            "BACKEND": "django.core.files.storage.FileSystemStorage",
            "OPTIONS": {
                "location": BASE_DIR / "backups",
            },
        },
    }
    # 备份最多数量
    DBBACKUP_CLEANUP_KEEP = 3
