# nginx配置

server {
    listen 80;
    listen [::]:80; # ipv6
    server_name xxxx.com;

    # 静态文件（对应 Django collectstatic 的 STATIC_ROOT）
    location /static/ {
        alias /var/www/html/XXXXX/staticfiles/;
    }
    # 媒体文件（对应 Django MEDIA_ROOT）
    location /media/ {
        alias /var/www/html/XXXXX/media/;
    }

    # 反代 Django/Gunicorn
	location / {
	    proxy_pass http://127.0.0.1:6688;
	    proxy_set_header Host $host;
	    # 确保这一行存在，让 Django 知道原始请求是 https
	    proxy_set_header X-Forwarded-Proto $scheme; 
	    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
	}
}